# Generated by Django 4.2.7 on 2023-12-11 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DIP', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.profile'),
        ),
    ]
