# Generated by Django 4.2.5 on 2023-10-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIP', '0002_rename_blog_dip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
            ],
        ),
    ]
