# Generated by Django 4.2.5 on 2023-10-05 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DIP', '0004_remove_aboutpage_body_remove_aboutpage_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutPage',
            new_name='Sprint',
        ),
    ]
