# Generated by Django 4.2.5 on 2023-10-05 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DIP', '0005_rename_aboutpage_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='sprint_info',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
