# Generated by Django 4.2.6 on 2023-10-19 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DIP', '0006_sprint_sprint_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('user_FName', models.CharField(max_length=250)),
                ('user_LName', models.CharField(max_length=250)),
                ('user_Password', models.CharField(max_length=250)),
                ('user_LoginName', models.CharField(max_length=250)),
                ('user_Type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorCo', models.CharField(max_length=250)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=250)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIP.user')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportType', models.CharField(max_length=250)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIP.user')),
            ],
        ),
    ]
