# Generated by Django 4.2.6 on 2023-10-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DIP', '0007_user_driver'),
        ('DIP', '0007_user_sponsor_driver_admin'),
    ]

    operations = [
    ]
