# Generated by Django 4.2.6 on 2023-10-25 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DIP', '0008_merge_0007_user_driver_0007_user_sponsor_driver_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='driver',
            name='wallet',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
