# Generated by Django 4.2.7 on 2023-11-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIP', '0008_mymodel_sprint_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='mysprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamNum', models.IntegerField()),
                ('versNum', models.CharField(max_length=250)),
                ('releaseDate', models.CharField(max_length=250)),
                ('prodDesc', models.CharField(max_length=250)),
            ],
        ),
    ]
