# Generated by Django 4.2.7 on 2023-11-28 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DIP', '0009_mysprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250, verbose_name='first name')),
                ('lastName', models.CharField(max_length=250, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('username', models.CharField(max_length=250, verbose_name='username')),
                ('password', models.CharField(max_length=250, verbose_name='password')),
                ('role', models.CharField(max_length=1, verbose_name='role')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_LoginName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_Password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_Type',
        ),
        migrations.AddField(
            model_name='user',
            name='user_New',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DIP.newuser'),
        ),
    ]
