# Generated by Django 4.2.6 on 2023-11-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIP', '0010_newuser_delete_mymodel_remove_user_user_loginname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_FName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_LName',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.CharField(help_text='D(driver) S(sponsor) A(admin)', max_length=1, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
