# Generated by Django 4.2.5 on 2023-10-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DIP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='DIP',
        ),
    ]
