# Generated by Django 4.2.5 on 2023-10-05 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DIP', '0003_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='sprint',
            field=models.CharField(default=django.utils.timezone.now, help_text='current sprint', max_length=250),
            preserve_default=False,
        ),
    ]
