# Generated by Django 4.2.7 on 2023-12-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
