# Generated by Django 4.2.7 on 2023-12-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('driver', 'driver'), ('sponsor', 'sponsor'), ('admin', 'admin')], default='driver', max_length=7),
        ),
    ]
